// <auto-generated />
using FootballCrazeSweepstakes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballCrazeSweepstakes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250119180957_AddEticketEntity")]
    partial class AddEticketEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");
#pragma warning restore 612, 618
        }
    }
}
